-- WorldSmith Field Architecture foundation. Idempotent so existing editorial data is untouched.
CREATE TABLE IF NOT EXISTS ws_vocabularies (id text PRIMARY KEY, key text NOT NULL, label text NOT NULL, description text NOT NULL DEFAULT '', version integer NOT NULL DEFAULT 1, scope text NOT NULL DEFAULT 'global', world_id text, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_vocabulary_options (id text PRIMARY KEY, vocabulary_id text NOT NULL, key text NOT NULL, label text NOT NULL, description text NOT NULL DEFAULT '', display_order integer NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1, world_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_record_vocabulary_values (record_id text NOT NULL, vocabulary_id text NOT NULL, option_key text NOT NULL, custom_value text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(record_id,vocabulary_id,option_key));
CREATE TABLE IF NOT EXISTS ws_canon_record_aliases (id text PRIMARY KEY, record_id text NOT NULL, alias text NOT NULL, kind text NOT NULL DEFAULT 'alternate', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_canon_facts (id text PRIMARY KEY, record_id text NOT NULL, subject text NOT NULL, predicate text NOT NULL, value text NOT NULL, status text NOT NULL DEFAULT 'proposed', confidence text, visibility text, source_citation_ids jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_source_citations (id text PRIMARY KEY, world_id text NOT NULL, title text NOT NULL, citation text NOT NULL, source_type text, url text, notes text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_editorial_flags (id text PRIMARY KEY, world_id text NOT NULL, record_id text, severity text NOT NULL DEFAULT 'warning', code text NOT NULL, message text NOT NULL, status text NOT NULL DEFAULT 'open', rationale text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
DO $$ DECLARE n text; BEGIN FOREACH n IN ARRAY ARRAY['character','location','object','event','lore','atmosphere','motif'] LOOP EXECUTE format('CREATE TABLE IF NOT EXISTS ws_%s_profiles (record_id text PRIMARY KEY, schema_version integer NOT NULL DEFAULT 1, profile jsonb NOT NULL DEFAULT ''{}'', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())', n); END LOOP; END $$;
CREATE TABLE IF NOT EXISTS ws_character_life_stage_variants (id text PRIMARY KEY, record_id text NOT NULL, variant_name text NOT NULL, life_stage text NOT NULL, profile jsonb NOT NULL DEFAULT '{}', active boolean NOT NULL DEFAULT true, is_default boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_visual_identity_locks (id text PRIMARY KEY, record_id text NOT NULL, variant_id text, category text NOT NULL, value text NOT NULL, strength text NOT NULL DEFAULT 'preferred', positive_prompt text, negative_prompt text, explanation text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_knowledge_entries (id text PRIMARY KEY, record_id text NOT NULL, topic_record_id text, knowledge_state text NOT NULL, confidence text, source text, disclosure text, access text, belief text, objective_truth text, consequence text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_canon_relationships (id text PRIMARY KEY, world_id text NOT NULL, from_record_id text NOT NULL, to_record_id text NOT NULL, relationship_type jsonb NOT NULL DEFAULT '[]', phase text, trust text, details text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_assets (id text PRIMARY KEY, world_id text NOT NULL, record_id text NOT NULL, role text NOT NULL, variant_id text, title text NOT NULL, alt_text text NOT NULL DEFAULT '', object_path text, source text NOT NULL, rights_status text, approval_status text NOT NULL DEFAULT 'draft', canonical_strength text NOT NULL DEFAULT 'inspiration_only', mime_type text, width integer, height integer, byte_size integer, checksum text, generation_prompt text, generation_model text, positive_guidance text, negative_guidance text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_asset_links (asset_id text NOT NULL, record_id text NOT NULL, role text NOT NULL DEFAULT 'reference', variant_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(asset_id,record_id));
CREATE TABLE IF NOT EXISTS ws_story_beats (id text PRIMARY KEY, story_id text NOT NULL, world_id text NOT NULL, sort_order integer NOT NULL DEFAULT 0, beat_type text NOT NULL, title text NOT NULL, summary text NOT NULL DEFAULT '', details jsonb NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'draft', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_story_scene_details (scene_id text PRIMARY KEY, purpose text, viewpoint_distance text, details jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_reveal_threads (id text PRIMARY KEY, story_id text NOT NULL, world_id text NOT NULL, title text NOT NULL, truth text NOT NULL, audience_knowledge text, details jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ws_scene_anchors (id text PRIMARY KEY, world_id text NOT NULL, name text NOT NULL, details jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
-- Stable, global vocabulary roots. Options are extensible by world-scoped governance routes.
INSERT INTO ws_vocabularies (id,key,label,description,scope) VALUES
 ('canon-type','canon_type','Canon type','The kind of canon record.','global'),
 ('workflow-status','workflow_status','Workflow status','Editorial acceptance lifecycle.','global'),
 ('canon-stability','canon_stability','Canon stability','How firmly a fact is established.','global'),
 ('life-stage','life_stage','Life stage','A character age or story phase.','global'),
 ('asset-role','asset_role','Asset role','How an asset is used in generation.','global'),
 ('asset-approval','asset_approval','Asset approval','Whether an asset may be used.','global')
ON CONFLICT (id) DO NOTHING;
INSERT INTO ws_vocabulary_options (id,vocabulary_id,key,label,display_order) VALUES
 ('canon-character','canon-type','character','Character',10),('canon-location','canon-type','location','Location',20),('canon-object','canon-type','object','Object',30),('canon-event','canon-type','event','Event',40),('canon-lore','canon-type','lore','Lore',50),('canon-atmosphere','canon-type','atmosphere','Atmosphere',60),('canon-material','canon-type','material','Material',70),('canon-relationship','canon-type','relationship','Relationship',80),('canon-motif','canon-type','motif','Motif',90),
 ('workflow-draft','workflow-status','draft','Draft',10),('workflow-review','workflow-status','in_review','In Review',20),('workflow-accepted','workflow-status','accepted','Accepted',30),('workflow-superseded','workflow-status','superseded','Superseded',40),('workflow-archived','workflow-status','archived','Archived',50),
 ('stability-fluid','canon-stability','fluid','Fluid',10),('stability-developing','canon-stability','developing','Developing',20),('stability-stable','canon-stability','stable','Stable',30),('stability-locked','canon-stability','locked','Locked',40),
 ('life-infant','life-stage','infant','Infant',10),('life-child','life-stage','child','Child',20),('life-adolescent','life-stage','adolescent','Adolescent',30),('life-young-adult','life-stage','young_adult','Young Adult',40),('life-adult','life-stage','established_adult','Established Adult',50),('life-elder','life-stage','elder','Elder',60),
 ('asset-primary-portrait','asset-role','primary_portrait','Primary Portrait',10),('asset-life-stage','asset-role','life_stage_reference','Life-Stage Reference',20),('asset-location','asset-role','location_reference','Location Reference',30),('asset-generated','asset-role','generated_concept','Generated Concept',40),
 ('asset-draft','asset-approval','draft','Draft',10),('asset-candidate','asset-approval','candidate','Candidate',20),('asset-approved','asset-approval','approved','Approved',30),('asset-rejected','asset-approval','rejected','Rejected',40)
ON CONFLICT (id) DO NOTHING;
ALTER TABLE ws_canon_records ADD COLUMN IF NOT EXISTS global_metadata jsonb NOT NULL DEFAULT '{}';
ALTER TABLE ws_canon_records ADD COLUMN IF NOT EXISTS structured_profile jsonb NOT NULL DEFAULT '{}';
ALTER TABLE ws_canon_records ADD COLUMN IF NOT EXISTS generation_profile jsonb NOT NULL DEFAULT '{}';
ALTER TABLE ws_stories ADD COLUMN IF NOT EXISTS story_spine jsonb NOT NULL DEFAULT '[]';
ALTER TABLE ws_stories ADD COLUMN IF NOT EXISTS reveal_threads jsonb NOT NULL DEFAULT '[]';
ALTER TABLE ws_stories ADD COLUMN IF NOT EXISTS global_metadata jsonb NOT NULL DEFAULT '{}';
ALTER TABLE ws_stories ADD COLUMN IF NOT EXISTS reveal_architecture jsonb NOT NULL DEFAULT '[]';