ALTER TABLE "worldsmith_worlds"
  ADD COLUMN "world_premise" text,
  ADD COLUMN "foundational_history" text,
  ADD COLUMN "central_dramatic_question" text,
  ADD COLUMN "core_themes" jsonb DEFAULT '[]'::jsonb NOT NULL,
  ADD COLUMN "narrative_pillars" jsonb DEFAULT '[]'::jsonb NOT NULL,
  ADD COLUMN "historical_eras" jsonb DEFAULT '[]'::jsonb NOT NULL,
  ADD COLUMN "institutions" jsonb DEFAULT '[]'::jsonb NOT NULL,
  ADD COLUMN "economy_and_resources" text,
  ADD COLUMN "knowledge_and_authority" text,
  ADD COLUMN "current_world_state" text,
  ADD COLUMN "narrative_gravity" text,
  ADD COLUMN "conflict_grammar" text,
  ADD COLUMN "discovery_rules" text,
  ADD COLUMN "story_guardrails" jsonb DEFAULT '[]'::jsonb NOT NULL,
  ADD COLUMN "continuity_anchors" jsonb DEFAULT '[]'::jsonb NOT NULL,
  ADD COLUMN "open_questions" jsonb DEFAULT '[]'::jsonb NOT NULL,
  ADD COLUMN "visual_guardrails" jsonb DEFAULT '[]'::jsonb NOT NULL,
  ADD COLUMN "image_direction" text;