// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/solo-rpg/BranchingScenePath.tsx": () => import("../components/mockups/solo-rpg/BranchingScenePath.tsx"),
  "./components/mockups/solo-rpg/ComparisonMvp.tsx": () => import("../components/mockups/solo-rpg/ComparisonMvp.tsx"),
  "./components/mockups/solo-rpg/PromptDeck.tsx": () => import("../components/mockups/solo-rpg/PromptDeck.tsx"),
  "./components/mockups/solo-rpg/SoloJournalSession.tsx": () => import("../components/mockups/solo-rpg/SoloJournalSession.tsx"),
  "./components/mockups/worldsmith-redesign/StoryOverview.tsx": () => import("../components/mockups/worldsmith-redesign/StoryOverview.tsx"),
  "./components/mockups/worldsmith-redesign/TheConstellation.tsx": () => import("../components/mockups/worldsmith-redesign/TheConstellation.tsx"),
  "./components/mockups/worldsmith-redesign/TheScroll.tsx": () => import("../components/mockups/worldsmith-redesign/TheScroll.tsx"),
  "./components/mockups/worldsmith-redesign/TheStudio.tsx": () => import("../components/mockups/worldsmith-redesign/TheStudio.tsx"),
  "./components/mockups/worldsmith-redesign/TheSynthesis.tsx": () => import("../components/mockups/worldsmith-redesign/TheSynthesis.tsx"),
  "./components/mockups/worldsmith-redesign/WorldBible.tsx": () => import("../components/mockups/worldsmith-redesign/WorldBible.tsx"),
  "./components/mockups/worldsmith-editorial/EditorialStudio.tsx": () => import("../components/mockups/worldsmith-editorial/EditorialStudio.tsx"),
  "./components/mockups/worldsmith-editorial/EditorialStudioGraph.tsx": () => import("../components/mockups/worldsmith-editorial/EditorialStudioGraph.tsx"),
  "./components/mockups/worldsmith-editorial/NewAssetFlow.tsx": () => import("../components/mockups/worldsmith-editorial/NewAssetFlow.tsx"),
  "./components/mockups/worldsmith-editorial/OperationsDashboard.tsx": () => import("../components/mockups/worldsmith-editorial/OperationsDashboard.tsx")
};
