// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/worldsmith-redesign/TheConstellation.tsx": () => import("../components/mockups/worldsmith-redesign/TheConstellation.tsx"),
  "./components/mockups/worldsmith-redesign/TheScroll.tsx": () => import("../components/mockups/worldsmith-redesign/TheScroll.tsx"),
  "./components/mockups/worldsmith-redesign/TheStudio.tsx": () => import("../components/mockups/worldsmith-redesign/TheStudio.tsx"),
  "./components/mockups/worldsmith-editorial/EditorialStudio.tsx": () => import("../components/mockups/worldsmith-editorial/EditorialStudio.tsx"),
  "./components/mockups/worldsmith-editorial/EditorialStudioGraph.tsx": () => import("../components/mockups/worldsmith-editorial/EditorialStudioGraph.tsx"),
  "./components/mockups/worldsmith-editorial/NewAssetFlow.tsx": () => import("../components/mockups/worldsmith-editorial/NewAssetFlow.tsx"),
  "./components/mockups/worldsmith-editorial/OperationsDashboard.tsx": () => import("../components/mockups/worldsmith-editorial/OperationsDashboard.tsx")
};
